Nightlies (#1)
* fast forward

* remove dead function

* adding developer tools

* testing pod startup

* cloudctl pod devel

* cloudctl pod devel

* cloudctl pod devel

* cloudctl pod devel

* cloudctl pod devel

* cloudctl pod devel

* cloudctl pod devel

* add dev link

* typo

* visual

* fix tar name

* gh actions naming convention update

* add local build dev script

* update manual build script

* update manual build script

* update manual build script

* update manual build script

* update manual build script

* update manual build script

* add local build to doc

* disable pull always

* add local build to doc

* update entrypoint strategy

* update local build script

* update local build script

* update local build script

* update local build script

* update local build script

* update local build script

* update local build script

* update local build script

* update order of operations

* tweak local build

* fix dev entrypoint cli

* disable ubi-minimal for now

* testing dnf fixes

* update purge

* build troubleshooting

* build troubleshooting

* build troubleshooting

* build troubleshooting

* build troubleshooting

* build troubleshooting

* troubleshooting tweaks

* fix entrypoint

* formatting

* formatting

* formatting

* formatting

* remove time

* sudo

* docs reorg

* simplify

* simplify

* fix unpack cmd

* startup utility fixes

* startup utility fixes

* testing htpasswd

* error suppression

* add quick trick

* add quick trick

* add

* move to command module for bcrypt registry pwd

* fix auth htpasswd path

* refactor for sane module organization

* reorder

* add dir_ansible back in

* test

* testing

* cleanup

* cleanup

* cleanup

* koffer v1 success

diff --git a/templates/bin/start-cloudctl.sh.j2 b/templates/bin/start-cloudctl.sh.j2
--- a/templates/bin/start-cloudctl.sh.j2
+++ b/templates/bin/start-cloudctl.sh.j2
@@ -7,6 +7,7 @@ if [[ ! -d ./deploy ]]; then
   runUser="$USER"
 fi
 
+mkdir /root/deploy/nginx
 sudo chown -R ${runUser}:${runUser} ${HOME}/deploy
 
 run_clean () {
@@ -29,7 +30,7 @@ load_images () {
 
 load_mirror_certificate () {
 cp /root/deploy/secrets/registry/ssl/registry.crt \
-    /etc/pki/ca-trust/source/anchors/cloudctl-registry.crt \
+    /etc/pki/ca-trust/source/anchors/registry.crt \
   && sudo update-ca-trust
 }
 
@@ -41,7 +42,6 @@ run_core () {
   run_clean
   load_images
   load_mirror_certificate
-  write_mirror_credentials
   run_pod
 }
 
@@ -50,14 +50,14 @@ test_core () {
   echo " >> Testing NGINX Ignition Service"
   ignTest=$(curl http://localhost:8080/bootstrap.ign 2>&1 1>/dev/null ; echo $?)
   [[ ${ignTest} == '0' ]] \
-      && echo '  >> NGINX Ignition Delivery Service Failed!' \
-      || echo '  >> NGINX Ignition Delivery Service Online.'
+      && echo "  >> NGINX Ignition Delivery Service Failed!" \
+      || echo "  >> NGINX Ignition Delivery Service Online."
 
   echo " >> Testing Docker Registry:2 Service"
   ignTest=$(curl -u cloudctl:cloudctl -k https://localhost:5000/v2/_catalog 2>&1 1>/dev/null ; echo $?)
   [[ ${ignTest} == '0' ]] \
-      && echo '  >> Registry Service Failed!' \
-      || echo '  >> Registry Service Online. Catalog: $(curl -u cloudctl:cloudctl -k https://localhost:5000/v2/_catalog)'
+      && echo "  >> Registry Service Failed!" \
+      || echo "  >> Registry Service Online. Catalog: $(curl -u cloudctl:cloudctl -k https://localhost:5000/v2/_catalog)"
 
   echo " >> List Pods & Containers"
   podman pod ps
@@ -66,14 +66,3 @@ test_core () {
 
 run_core
 test_core
-cat <<EOF
-
-    Pod Startup Complete!
-    Registry is ready for hydration:
-
-    Example:
-
-        mkdir /root/.docker 2>/dev/null ; cp $(ls /root/deploy/*/.docker/mirror.json) /root/.docker/config.json
-        oc image mirror -a /root/.docker/mirror.json --dir=mirror file://openshift/release:4.4.9* registry.ocp4.clusterfudge.net:5000/ocp-4.4.9
-
-EOF
